Faster builds, with updates to documentation generation. Reading the multiple GATKText files as a single stream, especially with new top level target executable jar files pointing to a lib folder. Don't dirty the build with a new GATKText.properties if input files are unmodified. Stop warning on undocumented abstract classes. Fixed ClassNotFoundException/NoClassDefFoundError by fixing ResourceBundleExtractorDoclet artifact. Excluding Exceptions from documentation. Removed custom log4j dependency from ResourceBundleExtractorDoclet. Stop generating the dependency reduced pom during shade. Stop regenerating gsalib when the files are already up to date. Disabled mvn site generation from external-example.